default_job = "check"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets"]
need_stdout = false

# Run clippy on the default target
[jobs.clippy]
command = ["cargo", "clippy"]
need_stdout = false

# Run clippy on all targets
[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets"]
need_stdout = false

# This job lets you run all tests
[jobs.test]
command = ["cargo", "test"]
need_stdout = true

[jobs.nextest]
command = [
    "cargo",
    "nextest",
    "run",
    "--hide-progress-bar",
    "--failure-output",
    "final",
]
need_stdout = true
analyzer = "nextest"

[jobs.doc]
command = ["cargo", "doc", "--no-deps"]
need_stdout = false

[jobs.doc-open]
command = ["cargo", "doc", "--no-deps", "--open"]
need_stdout = false
on_success = "back"                               # so that we don't open the browser at each change

# Run the server (serverクレート) as a background job
[jobs.run]
command = ["cargo", "run", "-p", "server"]
need_stdout = true
allow_warnings = true
background = true

# Run the server in a long-running mode (foreground), with automatic restart on changes.
[jobs.run-long]
command = ["cargo", "run", "-p", "server"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

# This parameterized job runs the example of your choice.
[jobs.ex]
command = ["cargo", "run", "--example"]
need_stdout = true
allow_warnings = true

[keybindings]
c = "job:clippy-all" # Press 'c' to run clippy on all targets
